services:
  - type: web
    name: projetcomplet
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: askely-express-db
          property: connectionString
