services:
  - type: web
    name: askely-express
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: askely-express-db
          property: connectionString
    autoDeploy: true