

services:
  - type: web
    name: askely-formulaire-colis
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: askely-colis-db
          property: connectionString

databases:
  - name: askely-colis-db
    databaseName: askelycolis
    user: askelyuser

