services:
  - type: web
    name: askely-formulaire-colis
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
