databases:
- name: askely-db
  plan: free
  region: oregon
services:
- buildCommand: pip install -r requirements.txt
  env: python
  envVars:
    DATABASE_URL:
      fromService: askely-db
      property: connectionString
    OPENAI_API_KEY:
      sync: true
  name: askely-formulaire-colis
  plan: free
  startCommand: python app.py
  type: web
